name: werewolfs
version: '1.0-SNAPSHOT'
main: me.friedhof.werewolfs.Werewolfs
api-version: 1.19
commands:
  gui:
    description: Öffne das SpielleiterGui
    usage: /gui
    permission: Werewolfs.gui

permissions:
  Werewolfs.gui:
    default: op